// <auto-generated />
using System;
using MMBackUp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MMBackUp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230717135409_CreateInitial")]
    partial class CreateInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MMBackUp.Shared.FlightInfo", b =>
                {
                    b.Property<long?>("FlightLegId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("FlightLegId"));

                    b.Property<string>("AircraftCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("AircraftConfiguration")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("AircraftOwner")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ArrivalAirportCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CabinCrewEmployer")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CockpitCrewEmployer")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DepartureAirportCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("LegSequenceNumber")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("MaintenanceTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Prbd")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ServiceTypeCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("UtcFlightDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("FlightLegId");

                    b.ToTable("FlightInfos");

                    b.HasData(
                        new
                        {
                            FlightLegId = 1L,
                            AircraftCode = "god help me",
                            AircraftConfiguration = "oh its configured alright",
                            AircraftOwner = "saddaam hussein",
                            ArrivalAirportCode = "not obama",
                            CockpitCrewEmployer = "9/11",
                            CompanyCode = "PH.com",
                            DepartureAirportCode = "obama",
                            LegSequenceNumber = 69,
                            Prbd = "...",
                            ServiceTypeCode = "in the beginning, there was nothing"
                        },
                        new
                        {
                            FlightLegId = 2L,
                            AircraftCode = "god help me",
                            AircraftConfiguration = "oh its configured alright",
                            AircraftOwner = "saddaam hussein",
                            ArrivalAirportCode = "not obama",
                            CockpitCrewEmployer = "9/11",
                            CompanyCode = "PH.com",
                            DepartureAirportCode = "not obama D:",
                            LegSequenceNumber = 79,
                            Prbd = "...",
                            ServiceTypeCode = "in the beginning, there was nothing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
